Refactoring
MkpDolganovKirill/crypto_force_news pull request #3
Opened 2022-11-17 16:03 UTC by nnabse

2022-11-17 19:10 UTC, MkpDolganovKirill commented on src/app/app.module.ts
>  import { AbsolutePipe } from './pipes/absolute.pipe';
import ordering

2022-11-17 19:18 UTC, MkpDolganovKirill commented on src/app/app.module.ts
> +    MatAutocompleteModule,
Mat components need to switch to other file

2022-11-17 19:18 UTC, MkpDolganovKirill commented on src/app/components/left-side-bar/left-side-bar.component.scss
> +@import "src/variables";
@variables

2022-11-17 19:18 UTC, MkpDolganovKirill commented on src/app/pages/crypto-rates/crypto-rates.component.html
> +            src="https://s2.coinmarketcap.com/static/img/coins/64x64/{{
magic string

2022-11-17 19:18 UTC, MkpDolganovKirill commented on src/app/pages/crypto-rates/crypto-rates.component.html
> -        <th mat-header-cell *matHeaderCellDef> No. </th>
magic string

2022-11-17 19:18 UTC, MkpDolganovKirill commented on src/app/pages/crypto-rates/crypto-rates.component.html
> +              src="https://s2.coinmarketcap.com/static/img/coins/64x64/{{
magic string

2022-11-19 17:33 UTC, MkpDolganovKirill requested changes

2022-11-19 17:33 UTC, MkpDolganovKirill commented on src/app/pages/crypto-rates/crypto-rates.component.scss
> +  padding: 30px;
why did you change gap on padding?

2022-11-19 17:33 UTC, MkpDolganovKirill commented on src/app/pages/crypto-rates/crypto-rates.enums.ts
> +enum TableLink {
enum for one link? use constants

2022-11-19 17:33 UTC, MkpDolganovKirill commented on src/app/services/api.service.ts
> +          limit: 1000,
limit in constants or use this for change in UI

2022-11-19 17:33 UTC, MkpDolganovKirill commented on src/variables.scss
> +$secondary-color: #afbbf2;
two same variables

2022-11-21 10:50 UTC, nnabse commented on src/app/pages/crypto-rates/crypto-rates.component.scss
> +  padding: 30px;
its ur commit

2022-11-21 19:24 UTC, MkpDolganovKirill approved these changes

2022-11-21 19:25 UTC, merged